# Generated by Django 3.0.6 on 2020-05-25 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaudeDocumentoAfastamento',
            new_name='Atestado',
        ),
    ]
