# Generated by Django 3.0.6 on 2020-05-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_auto_20200525_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(verbose_name='Matricula')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
            ],
        ),
    ]
