# Generated by Django 3.0.6 on 2020-06-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0003_producao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaCid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(verbose_name='Matricula')),
                ('datainicial', models.DateField(verbose_name='Data Inicial')),
                ('datafinal', models.DateField(verbose_name='Data Final')),
                ('dias', models.IntegerField(verbose_name='Dias')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('afastamento', models.CharField(max_length=50, verbose_name='Afastamento')),
                ('cadastro', models.CharField(max_length=50, verbose_name='Cadastro')),
                ('cid', models.CharField(max_length=20, verbose_name='CID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sexo', models.CharField(max_length=15, verbose_name='Sexo')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('vinculo', models.CharField(max_length=30, verbose_name='Vinculo')),
                ('comarca', models.CharField(max_length=50, verbose_name='Comarca')),
                ('centroCusto', models.CharField(max_length=50, verbose_name='Centro de Custo')),
                ('apoioDiretoIndireto', models.CharField(max_length=50, verbose_name='Grau')),
                ('area', models.CharField(max_length=50, verbose_name='Area')),
                ('areasub', models.CharField(max_length=50, verbose_name='Sub Área')),
                ('maxlotaexer', models.CharField(max_length=50, verbose_name='Lotação')),
            ],
        ),
    ]
